query Vocabularies($first: Int, $levels: [String]){
  vocabularies(first: $first, levels: $levels) {
    pageInfo{
      endCursor
      startCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      id
      word
      level
      pos
      ox5000
    }
  }
}