# import '../fragment/vocabulary.gql'

query Vocabularies(
  $first: Int,
  $last: Int,
  $levels: [String],
  $after: String,
  $before: String,
  $keyword: String,
  $hasNote: Boolean
) {
  vocabularies(
    first: $first,
    last: $last,
    levels: $levels,
    after: $after,
    before: $before,
    keyword: $keyword,
    hasNote: $hasNote
  ) {
    totalCount
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node{
        ...VocabularyFields
      }
    }
  }
}
