# import '../fragment/definitions.gql'

query Vocabularies($levels: [String], $definitionFirst: Int) {
  vocabularies(levels: $levels) {
    id
    word
    level
    pos
    ox5000
    note {
      updatedAt
      definitions {
        ...definitionField
      }
    }
  }
}
